import { Material, StatsData } from "@/types";

export interface ExtendedMaterial extends Material {
  language: "uz" | "ru" | "en";
  topic: "forestry" | "landDegradation" | "climate" | "water" | "biodiversity" | "pastures";
  countryCode: "uz" | "kz" | "kg" | "tj" | "tm" | "regional";
}

export const mockMaterialsExtended: ExtendedMaterial[] = [
  {
    id: "mat-001",
    slug: "aral-sea-basin-afforestation-assessment-2024",
    title: "Orol dengizi tubida o'rmonzorlar barpo etish va monitoring natijalari",
    description: "Orolqum hududida qurg'oqchilikka chidamli saksovul va boshqa buta o'simliklarini ekish samaradorligining 5 yillik tahlili va ekologik ta'siri.",
    localizedTitle: {
      uz: "Orol dengizi tubida o'rmonzorlar barpo etish va monitoring natijalari",
      ru: "Создание лесных насаждений на осушенном дне Аральского моря и результаты мониторинга",
      en: "Afforestation and Monitoring Assessment on the Dried Bed of the Aral Sea",
    },
    localizedSummary: {
      uz: "Orolqum hududida qurg'oqchilikka chidamli saksovul va boshqa buta o'simliklarini ekish samaradorligining 5 yillik tahlili va ekologik ta'siri.",
      ru: "Пятилетний анализ эффективности и экологического воздействия посадки засухоустойчивого саксаула в регионе Аралкум.",
      en: "Five-year assessment of drought-resistant saxaul planting efficiency and environmental impact across the Aralkum desert.",
    },
    contentType: "report",
    country: "Uzbekistan",
    countryCode: "uz",
    topic: "forestry",
    language: "uz",
    year: 2024,
    author: "Dr. A. Rahimov, N. To'rayev",
    organization: "O'rmon xo'jaligi davlat qo'mitasi & RESILAND",
    publishedAt: "2024-11-15T08:30:00Z",
    updatedAt: "2024-11-16T10:00:00Z",
    downloadsCount: 1420,
    viewsCount: 3890,
    fileSize: "4.8 MB",
    fileType: "PDF",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["Orolbo'yi", "O'rmonlashtirish", "Cho'llanish", "Iqlim", "Saksovul"],
  },
  {
    id: "mat-002",
    slug: "central-asia-land-degradation-geospatial-dataset",
    title: "Markaziy Osiyo yer degradatsiyasi va vegetatsiya indeksi (NDVI) geofazoviy ma'lumotlar to'plami",
    description: "Sentinel-2 va Landsat-8 sun'iy yo'ldosh tasvirlari asosida 2018-2024 yillar oralig'idagi yer qoplami o'zgarishlari va degradatsiya xaritalari to'plami.",
    localizedTitle: {
      uz: "Markaziy Osiyo yer degradatsiyasi va vegetatsiya indeksi (NDVI) geofazoviy ma'lumotlar to'plami",
      ru: "Геопространственный набор данных о деградации земель и вегетационном индексе (NDVI) в Центральной Азии",
      en: "Central Asia Land Degradation and Vegetation Index (NDVI) Geospatial Dataset",
    },
    localizedSummary: {
      uz: "Sentinel-2 va Landsat-8 sun'iy yo'ldosh tasvirlari asosida 2018-2024 yillar oralig'idagi yer qoplami o'zgarishlari va degradatsiya xaritalari to'plami.",
      ru: "Набор карт изменений растительного покрова и деградации земель за 2018–2024 гг. на основе снимков Sentinel-2 и Landsat-8.",
      en: "Comprehensive dataset of land cover dynamics and degradation indices derived from Sentinel-2 and Landsat-8 imagery (2018-2024).",
    },
    contentType: "dataset",
    country: "Regional (CA+)",
    countryCode: "regional",
    topic: "landDegradation",
    language: "en",
    year: 2024,
    author: "Geofazoviy Tahlil Guruhi",
    organization: "RESILAND CA+ Regional Center",
    publishedAt: "2024-10-28T14:10:00Z",
    updatedAt: "2024-10-29T12:00:00Z",
    downloadsCount: 890,
    viewsCount: 2450,
    fileSize: "128 MB",
    fileType: "GeoJSON / GeoTIFF",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["GIS", "NDVI", "Yer degradatsiyasi", "Remote Sensing", "Sentinel"],
  },
  {
    id: "mat-003",
    slug: "pasture-management-guidelines-kyrgyzstan-mountains",
    title: "Tog'li yaylovlarni barqaror boshqarish va eroziyani kamaytirish bo'yicha amaliy qo'llanma",
    description: "Chorva mollarini navbatlab boqish, tog' yonbag'irlarida tuproq unumdorligini saqlash va mahalliy jamoalar uchun yaylov qo'mitalari faoliyati bo'yicha yo'riqnoma.",
    localizedTitle: {
      uz: "Tog'li yaylovlarni barqaror boshqarish va eroziyani kamaytirish bo'yicha amaliy qo'llanma",
      ru: "Практическое руководство по устойчивому управлению горными пастбищами и снижению эрозии",
      en: "Practical Guidelines for Sustainable Mountain Pasture Management and Soil Erosion Control",
    },
    localizedSummary: {
      uz: "Chorva mollarini navbatlab boqish, tog' yonbag'irlarida tuproq unumdorligini saqlash va mahalliy jamoalar uchun yaylov qo'mitalari faoliyati bo'yicha yo'riqnoma.",
      ru: "Руководство по ротационному выпасу скота, сохранению плодородия горных почв и работе пастбищных комитетов.",
      en: "Operational guidelines for rotational grazing, soil fertility preservation on mountain slopes, and local pasture user unions.",
    },
    contentType: "guideline",
    country: "Kyrgyzstan",
    countryCode: "kg",
    topic: "pastures",
    language: "ru",
    year: 2023,
    author: "B. Asanov, K. Mambetov",
    organization: "Qirg'iziston Qishloq xo'jaligi vazirligi",
    publishedAt: "2024-09-12T11:00:00Z",
    updatedAt: "2024-09-15T09:00:00Z",
    downloadsCount: 650,
    viewsCount: 1820,
    fileSize: "3.2 MB",
    fileType: "DOCX",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["Yaylovlar", "Tog' ekologiyasi", "Eroziya", "Barqarorlik"],
  },
  {
    id: "mat-004",
    slug: "water-efficiency-tajikistan-river-basins-study",
    title: "Vaxsh va Panj daryo havzalarida suvdan foydalanish samaradorligi va iqlimiy xatarlar",
    description: "Muzliklar erishi va daryo oqimi o'zgarishining qishloq xo'jaligi suv ta'minotiga ta'siri bo'yicha ilmiy monografiya va tavsiyalar.",
    localizedTitle: {
      uz: "Vaxsh va Panj daryo havzalarida suvdan foydalanish samaradorligi va iqlimiy xatarlar",
      ru: "Эффективность водопользования и климатические риски в бассейнах рек Вахш и Пяндж",
      en: "Water Use Efficiency and Climate Risks in the Vakhsh and Panj River Basins",
    },
    localizedSummary: {
      uz: "Muzliklar erishi va daryo oqimi o'zgarishining qishloq xo'jaligi suv ta'minotiga ta'siri bo'yicha ilmiy monografiya va tavsiyalar.",
      ru: "Научная монография о влиянии таяния ледников и изменения речного стока на водоснабжение сельского хозяйства.",
      en: "Research monograph on the impact of glacier retreat and runoff variability on agricultural water supply in Tajikistan.",
    },
    contentType: "publication",
    country: "Tajikistan",
    countryCode: "tj",
    topic: "water",
    language: "ru",
    year: 2024,
    author: "M. Saidov, T. Nabiyev",
    organization: "Suv muammolari instituti (Tojikiston)",
    publishedAt: "2024-08-20T09:45:00Z",
    updatedAt: "2024-08-22T11:30:00Z",
    downloadsCount: 1105,
    viewsCount: 2980,
    fileSize: "6.5 MB",
    fileType: "PDF",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["Suv resurslari", "Muzliklar", "Iqlim o'zgarishi", "Daryo havzasi"],
  },
  {
    id: "mat-005",
    slug: "kazakhstan-steppe-restoration-pilot-results",
    title: "Qozog'iston dasht ekotizimlarini qayta tiklash pilot loyihasi natijalari",
    description: "Shimoliy va Markaziy Qozog'iston dashtlarida biologik xilma-xillikni tiklash va degradatsiyaga uchragan yerlarni rekultivatsiya qilish usullari.",
    localizedTitle: {
      uz: "Qozog'iston dasht ekotizimlarini qayta tiklash pilot loyihasi natijalari",
      ru: "Результаты пилотного проекта по восстановлению степных экосистем Казахстана",
      en: "Results of the Pilot Project on Steppe Ecosystem Restoration in Kazakhstan",
    },
    localizedSummary: {
      uz: "Shimoliy va Markaziy Qozog'iston dashtlarida biologik xilma-xillikni tiklash va degradatsiyaga uchragan yerlarni rekultivatsiya qilish usullari.",
      ru: "Методы восстановления биоразнообразия и рекультивации деградированных земель в степях Северного и Центрального Казахстана.",
      en: "Methods for biodiversity recovery and land reclamation in degraded steppes of Northern and Central Kazakhstan.",
    },
    contentType: "report",
    country: "Kazakhstan",
    countryCode: "kz",
    topic: "biodiversity",
    language: "en",
    year: 2024,
    author: "S. Nurmaganbetov, E. Kassymov",
    organization: "Qozog'iston Ekologiya va tabiiy resurslar vazirligi",
    publishedAt: "2024-07-05T16:20:00Z",
    updatedAt: "2024-07-06T14:00:00Z",
    downloadsCount: 780,
    viewsCount: 2150,
    fileSize: "5.1 MB",
    fileType: "PDF",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["Dasht", "Biologik xilma-xillik", "Rekultivatsiya"],
  },
  {
    id: "mat-006",
    slug: "turkmenistan-karakum-desert-green-belt-initiative",
    title: "Qoraqum cho'lida yashil belbog' barpo etish va qum ko'chishini to'xtatish strategiyasi",
    description: "Magistral yo'llar va aholi punktlari atrofida fitomelioratsiya usullari yordamida qum ko'chishiga qarshi kurash bo'yicha qo'llanma.",
    localizedTitle: {
      uz: "Qoraqum cho'lida yashil belbog' barpo etish va qum ko'chishini to'xtatish strategiyasi",
      ru: "Стратегия создания зеленого пояса в пустыне Каракумы и остановки движения песков",
      en: "Strategy for Green Belt Development and Sand Dune Stabilization in Karakum Desert",
    },
    localizedSummary: {
      uz: "Magistral yo'llar va aholi punktlari atrofida fitomelioratsiya usullari yordamida qum ko'chishiga qarshi kurash bo'yicha qo'llanma.",
      ru: "Руководство по борьбе с подвижными песками методами фитомелиорации вдоль магистралей и населенных пунктов.",
      en: "Technical guidance on sand fixation and phytomelioration around transport corridors and rural settlements in Turkmenistan.",
    },
    contentType: "guideline",
    country: "Turkmenistan",
    countryCode: "tm",
    topic: "forestry",
    language: "ru",
    year: 2023,
    author: "G. Annayev, D. Berdiyev",
    organization: "Cho'llar, o'simlik va hayvonot olami milliy instituti",
    publishedAt: "2024-06-18T10:15:00Z",
    updatedAt: "2024-06-20T08:00:00Z",
    downloadsCount: 520,
    viewsCount: 1640,
    fileSize: "2.9 MB",
    fileType: "PDF",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["Qoraqum", "Qum ko'chishi", "Fitomelioratsiya", "Cho'llar"],
  },
  {
    id: "mat-007",
    slug: "climate-resilience-central-asia-agriculture-2024",
    title: "Iqlim o'zgarishiga moslashuvchan agrotexnologiyalar: Markaziy Osiyo fermerlari uchun tajribalar",
    description: "Tomchilatib sug'orish, tuproqni minimal ishlov berish va qurg'oqchilikka chidamli ekin navlarini ekish bo'yicha mintaqaviy tavsiyalar to'plami.",
    localizedTitle: {
      uz: "Iqlim o'zgarishiga moslashuvchan agrotexnologiyalar: Markaziy Osiyo fermerlari uchun tajribalar",
      ru: "Климатически устойчивые агротехнологии: опыт для фермеров Центральной Азии",
      en: "Climate-Resilient Agricultural Practices: Insights for Central Asian Farmers",
    },
    localizedSummary: {
      uz: "Tomchilatib sug'orish, tuproqni minimal ishlov berish va qurg'oqchilikka chidamli ekin navlarini ekish bo'yicha mintaqaviy tavsiyalar to'plami.",
      ru: "Сборник региональных рекомендаций по капельному орошению, минимальной обработке почвы и засухоустойчивым сортам.",
      en: "Regional recommendations on drip irrigation, minimum tillage, and drought-tolerant crop cultivars for smallholders.",
    },
    contentType: "publication",
    country: "Uzbekistan",
    countryCode: "uz",
    topic: "climate",
    language: "uz",
    year: 2024,
    author: "J. Yo'ldoshev, K. Ismoilov",
    organization: "Qishloq xo'jaligi ilmiy-ishlab chiqarish markazi",
    publishedAt: "2024-05-14T09:00:00Z",
    updatedAt: "2024-05-15T11:00:00Z",
    downloadsCount: 940,
    viewsCount: 2750,
    fileSize: "7.1 MB",
    fileType: "PDF",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["Iqlim", "Agro", "Suv tejash", "O'zbekiston"],
  },
  {
    id: "mat-008",
    slug: "tien-shan-glaciers-monitoring-database-2024",
    title: "Tyan-Shan muzliklari degradatsiyasi va gidrologik o'zgarishlar geoma'lumotlar bazasi",
    description: "Tyan-Shan tog' tizmasidagi asosiy muzliklarning maydoni, qalinligi va erish tezligi bo'yicha 10 yillik sun'iy yo'ldosh radarlari ma'lumotlari.",
    localizedTitle: {
      uz: "Tyan-Shan muzliklari degradatsiyasi va gidrologik o'zgarishlar geoma'lumotlar bazasi",
      ru: "База геоданных деградации ледников Тянь-Шаня и гидрологических изменений",
      en: "Tien Shan Glaciers Degradation and Hydrological Dynamics Geodatabase",
    },
    localizedSummary: {
      uz: "Tyan-Shan tog' tizmasidagi asosiy muzliklarning maydoni, qalinligi va erish tezligi bo'yicha 10 yillik sun'iy yo'ldosh radarlari ma'lumotlari.",
      ru: "Десятилетние данные спутниковых радаров о площади, толщине и скорости таяния основных ледников Тянь-Шаня.",
      en: "Decadal satellite radar observations on glacier surface area, ice thickness, and melt rates in the Tien Shan range.",
    },
    contentType: "dataset",
    country: "Kyrgyzstan",
    countryCode: "kg",
    topic: "water",
    language: "en",
    year: 2024,
    author: "Muzliklar Tadqiqoti Markazi",
    organization: "Markaziy Osiyo Amaliy Tadqiqotlar Instituti",
    publishedAt: "2024-04-10T15:30:00Z",
    updatedAt: "2024-04-12T14:00:00Z",
    downloadsCount: 1250,
    viewsCount: 3400,
    fileSize: "210 MB",
    fileType: "NetCDF / CSV",
    fileUrl: "https://pdfobject.com/pdf/sample.pdf",
    tags: ["Muzliklar", "Tyan-Shan", "Gidrologiya", "Geofazoviy"],
  },
];

export const mockMaterials = mockMaterialsExtended;

export const mockStats: StatsData = {
  totalMaterials: 486,
  totalDatasets: 74,
  totalPublications: 215,
  totalReports: 132,
  totalGuidelines: 65,
  byCountry: [
    { country: "Uzbekistan", count: 142 },
    { country: "Kazakhstan", count: 118 },
    { country: "Kyrgyzstan", count: 86 },
    { country: "Tajikistan", count: 72 },
    { country: "Turkmenistan", count: 45 },
    { country: "Regional (CA+)", count: 23 },
  ],
  lastAddedAt: "2024-11-15T08:30:00Z",
};
